import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <nav>
          <img />
          <Link href='/' passHref={ true }>Home</Link>
          <Link href='/events' passHref={ true }>events</Link>
          <Link href='/about-us' passHref={ true }>About us</Link>
        </nav>

      </header>


      <main className={styles.main}>
      {data.map(ev => 
      <Link href={`/events/${ev.id}`} key={ev.id} passHref={ true }>
        {/* <Image src={ev.image} alt={ev.title} width={200} height={200}/> */}
        <img src={ev.image} alt={ev.title} ></img>
        <h2>{ev.title}</h2>
        <p>{ev.description}</p>
      </Link>
      )}
      </main>
      <footer className={styles.footer}>
        <p>lorem ipsom</p>
      </footer>
    </>
  )
}

export async function getServerSideProps(){
  const { events_categories } = await import('../data/data.json')
  return{
      props:{
          data: events_categories
      }
  }
}